# Generated by Django 3.1.4 on 2021-01-12 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_delete_tbl_logins'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_user',
        ),
    ]
