# Generated by Django 3.1.4 on 2021-01-13 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_tbl_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_user',
        ),
    ]
