# Generated by Django 3.1.4 on 2021-01-13 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0009_tbl_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_login',
        ),
    ]
